{
 "title": "AppMesh / Virtual Node",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Mesh",
    "query": {
     "query": "label_values(envoy_server_live, Mesh)"
    }
   },
   {
    "name": "VirtualNode",
    "query": {
     "query": "label_values(envoy_server_live, VirtualNode)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Traffic",
   "type": "timeseries",
   "description": "App Mesh in/out traffic",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_rx_bytes_total{Mesh=~\"$Mesh\", VirtualNode=~\"$VirtualNode\"}[1m]))",
     "legendFormat": "Inbound"
    },
    {
     "expr": "-sum(rate(envoy_cluster_upstream_cx_tx_bytes_total{Mesh=~\"$Mesh\", VirtualNode=~\"$VirtualNode\"}[1m]))",
     "legendFormat": "Outbound"
    }
   ]
  },
  { "title": "Percentile", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "99th percentile of response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_appmesh_TargetResponseTime_bucket{Mesh=~\"$Mesh\", VirtualNode=~\"$VirtualNode\"}[1m])) by (le, TargetVirtualNode))",
     "legendFormat": "{{TargetVirtualNode}}"
    }
   ]
  },
  {
   "title": "95th percentile of response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_appmesh_TargetResponseTime_bucket{Mesh=~\"$Mesh\", VirtualNode=~\"$VirtualNode\"}[1m])) by (le, TargetVirtualNode))",
     "legendFormat": "{{TargetVirtualNode}}"
    }
   ]
  },
  {
   "title": "90th percentile of response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(envoy_appmesh_TargetResponseTime_bucket{Mesh=~\"$Mesh\", VirtualNode=~\"$VirtualNode\"}[1m])) by (le, TargetVirtualNode))",
     "legendFormat": "{{TargetVirtualNode}}"
    }
   ]
  },
  { "title": "Response codes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "2xx Response by target virtual node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_appmesh_HTTPCode_Target_2XX_Count{Mesh=~\"$Mesh\", VirtualNode=~\"$VirtualNode\"}[1m])) by (TargetVirtualNode)",
     "legendFormat": "{{TargetVirtualNode}}"
    }
   ]
  },
  {
   "title": "Egress 3xx Response by target virtual node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_appmesh_HTTPCode_Target_3XX_Count{Mesh=~\"$Mesh\", VirtualNode=~\"$VirtualNode\"}[1m])) by (TargetVirtualNode)",
     "legendFormat": "{{TargetVirtualNode}}"
    }
   ]
  },
  {
   "title": "Egress 4xx Response by target virtual node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_appmesh_HTTPCode_Target_4XX_Count{Mesh=~\"$Mesh\", VirtualNode=~\"$VirtualNode\"}[1m])) by (TargetVirtualNode)",
     "legendFormat": "{{TargetVirtualNode}}"
    }
   ]
  },
  {
   "title": "Egress 5xx Response by target virtual node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_appmesh_HTTPCode_Target_5XX_Count{Mesh=~\"$Mesh\", VirtualNode=~\"$VirtualNode\"}[1m])) by (TargetVirtualNode)",
     "legendFormat": "{{TargetVirtualNode}}"
    }
   ]
  }
 ]
}