{
 "title": "AppMesh / Data Plane",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Mesh",
    "query": {
     "query": "label_values(envoy_server_live, Mesh)"
    }
   },
   {
    "name": "VirtualNode",
    "query": {
     "query": "label_values(envoy_server_live, VirtualNode)"
    }
   },
   {
    "name": "VirtualGateway",
    "query": {
     "query": "label_values(envoy_server_live, VirtualGateway)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Envoy Sidecars",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(envoy_server_live{Mesh=~\"$Mesh\", VirtualNode=~\"$VirtualNode\", VirtualGateway=~\"$VirtualGateway\"})"
    }
   ]
  },
  {
   "title": "Unhealthy Sidecars ",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(envoy_cluster_membership_total{Mesh=~\"$Mesh\", VirtualNode=~\"$VirtualNode\", VirtualGateway=~\"$VirtualGateway\"})  - sum(envoy_cluster_membership_healthy{Mesh=~\"$Mesh\", VirtualNode=~\"$VirtualNode\", VirtualGateway=~\"$VirtualGateway\"}))"
    }
   ]
  },
  {
   "title": "Envoy Restarts (last 24 hours)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(envoy_server_hot_restart_epoch{Mesh=~\"$Mesh\", VirtualNode=~\"$VirtualNode\", VirtualGateway=~\"$VirtualGateway\"}[24h]))"
    }
   ]
  },
  {
   "title": "SSL Errors (last 24 hours)",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_ssl_fail_verify_cert_hash{Mesh=~\"$Mesh\", VirtualNode=~\"$VirtualNode\", VirtualGateway=~\"$VirtualGateway\"}[24h]))",
     "legendFormat": "Cluster Cert Hash"
    },
    {
     "expr": "sum(increase(envoy_cluster_ssl_fail_verify_error{Mesh=~\"$Mesh\", VirtualNode=~\"$VirtualNode\", VirtualGateway=~\"$VirtualGateway\"}[24h]))",
     "legendFormat": "Cluster Error"
    },
    {
     "expr": "sum(increase(envoy_cluster_ssl_fail_verify_no_cert{Mesh=~\"$Mesh\", VirtualNode=~\"$VirtualNode\", VirtualGateway=~\"$VirtualGateway\"}[24h]))",
     "legendFormat": "Cluster No Cert"
    },
    {
     "expr": "sum(increase(envoy_cluster_ssl_fail_verify_san{Mesh=~\"$Mesh\", VirtualNode=~\"$VirtualNode\", VirtualGateway=~\"$VirtualGateway\"}[24h]))",
     "legendFormat": "Cluster SAN"
    },
    {
     "expr": "sum(increase(envoy_listener_ssl_fail_verify_cert_hash{Mesh=~\"$Mesh\", VirtualNode=~\"$VirtualNode\", VirtualGateway=~\"$VirtualGateway\"}[24h]))",
     "legendFormat": "Listener Cert Hash"
    },
    {
     "expr": "sum(increase(envoy_listener_ssl_fail_verify_error{Mesh=~\"$Mesh\", VirtualNode=~\"$VirtualNode\", VirtualGateway=~\"$VirtualGateway\"}[24h]))",
     "legendFormat": "Listener Error"
    },
    {
     "expr": "sum(increase(envoy_listener_ssl_fail_verify_no_cert{Mesh=~\"$Mesh\", VirtualNode=~\"$VirtualNode\", VirtualGateway=~\"$VirtualGateway\"}[24h]))",
     "legendFormat": "Listener No Cert"
    },
    {
     "expr": "sum(increase(envoy_listener_ssl_fail_verify_san{Mesh=~\"$Mesh\", VirtualNode=~\"$VirtualNode\", VirtualGateway=~\"$VirtualGateway\"}[24h]))",
     "legendFormat": "Listener SAN"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "description": "App Mesh sidecars total inbound connections",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(envoy_http_downstream_cx_active{Mesh=~\"$Mesh\", VirtualNode=~\"$VirtualNode\", VirtualGateway=~\"$VirtualGateway\"})",
     "legendFormat": "Total connections"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Traffic",
   "type": "timeseries",
   "description": "App Mesh in/out traffic",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_rx_bytes_total{Mesh=~\"$Mesh\", VirtualNode=~\"$VirtualNode\", VirtualGateway=~\"$VirtualGateway\"}[1m]))",
     "legendFormat": "Inbound"
    },
    {
     "expr": "-sum(rate(envoy_cluster_upstream_cx_tx_bytes_total{Mesh=~\"$Mesh\", VirtualNode=~\"$VirtualNode\", VirtualGateway=~\"$VirtualGateway\"}[1m]))",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "Envoy 2xx Requests",
   "type": "timeseries",
   "description": "App Mesh Envoy success HTTP requests per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq{envoy_response_code=~\"2.*\", envoy_cluster_name=~\"cds_egress.*\", Mesh=~\"$Mesh\", VirtualNode=~\"$VirtualNode\", VirtualGateway=~\"$VirtualGateway\" }[1m]))",
     "legendFormat": "2xx"
    }
   ]
  },
  {
   "title": "Envoy 5xx/4xx Requests",
   "type": "timeseries",
   "description": "App Mesh Envoy failed HTTP requests per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq{envoy_response_code=~\"5.*\", envoy_cluster_name=~\"cds_egress.*\", Mesh=~\"$Mesh\", VirtualNode=~\"$VirtualNode\", VirtualGateway=~\"$VirtualGateway\"}[1m]))",
     "legendFormat": "5xx"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq{envoy_response_code=~\"4.*\", envoy_cluster_name=~\"cds_egress.*\", Mesh=~\"$Mesh\", VirtualNode=~\"$VirtualNode\", VirtualGateway=~\"$VirtualGateway\"}[1m]))",
     "legendFormat": "4xx"
    }
   ]
  },
  { "title": "SSL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Successful TLS connections",
   "type": "timeseries",
   "description": "Total successful TLS connection handshakes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_ssl_handshake{Mesh=~\"$Mesh\", VirtualNode=~\"$VirtualNode\", VirtualGateway=~\"$VirtualGateway\"}[1m]))"
    },
    {
     "expr": "sum(rate(envoy_listener_ssl_handshake{Mesh=~\"$Mesh\", VirtualNode=~\"$VirtualNode\", VirtualGateway=~\"$VirtualGateway\"}[1m]))"
    }
   ]
  },
  {
   "title": "SSL Failures - Missing Client Cert",
   "type": "timeseries",
   "description": "Total TLS connections that failed because of missing client certificate",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_ssl_fail_verify_no_cert{Mesh=~\"$Mesh\", VirtualNode=~\"$VirtualNode\", VirtualGateway=~\"$VirtualGateway\"}[1m]))"
    },
    {
     "expr": "sum(rate(envoy_listener_ssl_fail_verify_no_cert{Mesh=~\"$Mesh\", VirtualNode=~\"$VirtualNode\", VirtualGateway=~\"$VirtualGateway\"}[1m]))"
    }
   ]
  },
  {
   "title": "SSL - SAN Verification Failures",
   "type": "timeseries",
   "description": "Total TLS connections that failed SAN verification",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_ssl_fail_verify_san{Mesh=~\"$Mesh\", VirtualNode=~\"$VirtualNode\", VirtualGateway=~\"$VirtualGateway\"}[1m]))"
    },
    {
     "expr": "sum(rate(envoy_listener_ssl_fail_verify_san{Mesh=~\"$Mesh\", VirtualNode=~\"$VirtualNode\", VirtualGateway=~\"$VirtualGateway\"}[1m]))"
    }
   ]
  },
  {
   "title": "SSL - CA Verification Failures",
   "type": "timeseries",
   "description": "Total TLS connections that failed CA verification",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_ssl_fail_verify_error{Mesh=~\"$Mesh\", VirtualNode=~\"$VirtualNode\", VirtualGateway=~\"$VirtualGateway\"}[1m]))"
    },
    {
     "expr": "sum(rate(envoy_listener_ssl_fail_verify_error{Mesh=~\"$Mesh\", VirtualNode=~\"$VirtualNode\", VirtualGateway=~\"$VirtualGateway\"}[1m]))"
    }
   ]
  },
  {
   "title": "SSL Connection errors",
   "type": "timeseries",
   "description": "Total TLS connection errors not including failed certificate verifications",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_ssl_connection_error{Mesh=~\"$Mesh\", VirtualNode=~\"$VirtualNode\", VirtualGateway=~\"$VirtualGateway\"}[1m]))"
    },
    {
     "expr": "sum(rate(envoy_listener_ssl_connection_error{Mesh=~\"$Mesh\", VirtualNode=~\"$VirtualNode\", VirtualGateway=~\"$VirtualGateway\"}[1m]))"
    }
   ]
  },
  { "title": "Timeouts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Connection Timeout",
   "type": "timeseries",
   "description": "Total connection connect timeouts",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_connect_timeout{Mesh=~\"$Mesh\", VirtualNode=~\"$VirtualNode\", VirtualGateway=~\"$VirtualGateway\"}[1m]))"
    }
   ]
  },
  {
   "title": "Request Timeout",
   "type": "timeseries",
   "description": "Total requests that timed out waiting for a response",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_timeout{Mesh=~\"$Mesh\", VirtualNode=~\"$VirtualNode\", VirtualGateway=~\"$VirtualGateway\"}[1m]))"
    }
   ]
  },
  { "title": "Envoy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Envoy Memory Usage",
   "type": "timeseries",
   "description": "App Mesh Envoy sidecar containers memory working",
   "gridPos": { "h": 21, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage{container_name=\"envoy\"}) by (aws_ecs_task_family)",
     "legendFormat": "{{aws_ecs_task_family}}"
    }
   ]
  },
  {
   "title": "Envoy CPU Usage",
   "type": "timeseries",
   "description": "App Mesh Envoy sidecar containers CPU usage seconds total",
   "gridPos": { "h": 21, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_system{container_name=\"envoy\"}[1m])) by (aws_ecs_task_family)",
     "legendFormat": "{{aws_ecs_task_family}}"
    }
   ]
  },
  { "title": "Ejections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "Connection(cx) circuit breakers",
   "type": "timeseries",
   "description": "Number of connection circuit breakers for a namespace. Envoy metric: cx_open",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(envoy_cluster_circuit_breakers_default_cx_open{Mesh=~\"$Mesh\", VirtualNode=~\"$VirtualNode\", VirtualGateway=~\"$VirtualGateway\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Requests (rq) circuit breakers",
   "type": "timeseries",
   "description": "Number of request circuit breakers for a namespace. Envoy metric: rq_open",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(envoy_cluster_circuit_breakers_default_rq_open{Mesh=~\"$Mesh\", VirtualNode=~\"$VirtualNode\", VirtualGateway=~\"$VirtualGateway\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}